apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-clone-app:1.0.0-6
  template:
    metadata:
      labels:
        app: reddit-clone-app:1.0.0-6
    spec:
      containers:
        - name: reddit-clone-app:1.0.0-6
          image: vkrishna8/reddit-clone-app:1.0.0-6
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
